import { test, expect } from '@playwright/test'

test('intent form and stress test preserve honest evidence across all scenarios', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Your signature. Your terms.' })).toBeVisible()
  await page.getByRole('button', { name: 'Test my intent' }).click()
  await expect(page.getByRole('status')).toContainText('Local model · Conditions satisfied')
  await expect(page.getByText('The deal holds.')).toBeVisible()
  await page.getByRole('tab', { name: '02 A short receipt' }).click()
  await page.getByRole('button', { name: 'Run this scenario' }).click()
  await expect(page.getByRole('status')).toContainText('Local model · Intent blocked')
  await expect(page.getByText('Minimum receipt not met. The model discards all changes.')).toBeVisible()
  await page.getByRole('tab', { name: '03 A hidden approval' }).click()
  await page.getByRole('button', { name: 'Run this scenario' }).click()
  await expect(page.getByText('Token approval forbidden. The model discards all changes.')).toBeVisible()
  await page.getByRole('button', { name: /^Receipts/ }).click()
  await expect(page.locator('.receipt-record')).toHaveCount(3)
  await expect(page.locator('a[href*="/tx/"]')).toHaveCount(0)
  await expect(page.getByRole('dialog')).toContainText('Local demo')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('invalid terms and contract settings remain honest and dialogs trap focus', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Maximum spending amount').fill('-1')
  await page.getByRole('button', { name: 'Test my intent' }).click()
  await expect(page.getByText('Enter a positive decimal amount.')).toBeVisible()
  await page.getByRole('button', { name: 'Deployment settings' }).click()
  await page.getByRole('button', { name: 'Save testnet configuration' }).click()
  await expect(page.getByRole('dialog').getByText('Enter a valid contract address for account.')).toBeVisible()
  await page.getByRole('button', { name: 'Save testnet configuration' }).focus()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Close dialog' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.locator('summary').filter({ hasText: 'Is the demo real on-chain protection?' }).click()
  await expect(page.getByText(/The interactive demo is an explanatory local model/)).toBeVisible()
})

test('layouts, mobile navigation and local fonts work without external requests', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route(/^https?:\/\/(?!127\.0\.0\.1)/, route => route.abort())
  await page.setViewportSize({ width: 1440, height: 1050 })
  await page.goto('/')
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  for (const width of [1024, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Toggle navigation' }).click()
  await page.getByRole('button', { name: 'Receipts', exact: true }).click()
  await expect(page.getByText('No receipts yet.')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Test my intent' }).click()
  await expect(page.getByText('The deal holds.')).toBeVisible()
  expect(await page.evaluate(() => document.fonts.check('16px "Archivo"'))).toBe(true)
  expect(errors).toEqual([])
})
