import { test, expect } from '@playwright/test'

test('default Testnet form shows real asset identities and creates no fabricated receipts', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Your signature. Your terms.' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Preview', exact: true })).toHaveCount(0)
  await expect(page.locator('#stress-test')).toHaveCount(0)
  await expect(page.getByRole('img', { name: 'Stellar logo' })).toBeVisible()
  await expect(page.getByRole('img', { name: 'USDC logo' })).toBeVisible()
  await expect(page.getByLabel('Maximum spending amount')).toHaveValue('1')
  await expect(page.getByText('Auto minimum · 1% tolerance', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Connect testnet wallet', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^Receipts/ }).click()
  await expect(page.getByText('No receipts yet.')).toBeVisible()
  await expect(page.locator('.receipt-record')).toHaveCount(0)
  await expect(page.locator('a[href*="/tx/"]')).toHaveCount(0)
  await expect(page.getByRole('dialog')).toContainText('Submitted Testnet transactions')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('invalid terms and contract settings remain honest and dialogs trap focus', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Maximum spending amount').fill('-1')
  await page.getByRole('button', { name: 'Connect testnet wallet', exact: true }).click()
  await expect(page.getByText('Enter a positive decimal amount.')).toBeVisible()
  await page.getByRole('button', { name: 'Deployment settings' }).click()
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Connect testnet wallet', exact: true })).toBeVisible()
  await page.getByText('Recover funds from an earlier account', { exact: true }).click()
  await page.getByRole('button', { name: 'Save recovery account' }).click()
  await expect(page.getByRole('dialog').getByText('Enter a valid contract address for account.')).toBeVisible()
  await page.getByRole('button', { name: 'Save recovery account' }).focus()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Close dialog' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.locator('summary').filter({ hasText: 'Does this use real contracts?' }).click()
  await expect(page.getByText(/Trades use pinned Soroswap contracts on the selected Stellar network/)).toBeVisible()
})

test('layouts, mobile navigation and local fonts work without external requests', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route(/^https?:\/\/(?!127\.0\.0\.1)/, route => route.abort())
  await page.setViewportSize({ width: 1440, height: 1050 })
  await page.goto('/')
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  for (const width of [1024, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Toggle navigation' }).click()
  await page.getByRole('button', { name: 'Receipts', exact: true }).click()
  await expect(page.getByText('No receipts yet.')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('img', { name: 'Stellar logo' })).toBeVisible()
  await expect(page.getByRole('img', { name: 'USDC logo' })).toBeVisible()
  expect(await page.evaluate(() => document.fonts.check('16px "Archivo"'))).toBe(true)
  expect(errors).toEqual([])
})

test('a submitted protected action survives reload and blocks another preparation', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('caveat-action-pending', JSON.stringify({ hash: 'a'.repeat(64), source: 'GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF', action: 'liquidity' })))
  await page.route('**/src/lib/stellar.ts*', route => route.fulfill({ contentType: 'application/javascript', body: `export async function restoreWallet() { return ''; } export async function transactionStatus(hash) { return { hash, status: 'pending' }; }` }))
  await page.goto('/')
  await expect(page.getByRole('dialog', { name: 'Transaction status' })).toContainText('Awaiting confirmation')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page.getByRole('button', { name: 'Check submitted action' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Prepare & review intent' })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('dialog', { name: 'Transaction status' })).toContainText('Awaiting confirmation')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page.getByRole('button', { name: 'Check submitted action' })).toBeEnabled()
  await expect(page.getByText('An action is awaiting confirmation. Check it before preparing another.')).toHaveCount(0)
  await expect(page.getByText('Testnet · confirmed')).toHaveCount(0)
})
